### ISSUE TITLE
i have some problems and i need help

### ISSUE THREAD

**Issue by 69420-cell** [Agent-11/agent-ex-coop-mods#3]
so i cant load any of the mods for some reason and my controller a (seisa ps2 knockoff controller) doesnt work with coop dx i hope i'm not anoying you guys too much i barely know how to use this platform

**Comment by eros71-dev** [comment]
The repo for Coop DX isn't this one, you should probably post the issue there instead.
Also give us some more info so we can help you faster if you can, things like what OS and what version of the game you're using for example, and don't worry it's ok if you don't understand how github works entirely :)

Here's the link to the CoopDX issues page:
https://github.com/coop-deluxe/sm64coopdx/issues
